language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=mysql
bundler_args: '--without development'
before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate'
script: true
notifications:
  email: false
