language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=mysql
bundler_args: '--without development'
before_script:
  - 'RAILS_ENV=test bundle exec rake db:create'
script:
  - 'bundle exec rake db:test:prepare'
  - 'bundle exec rake spec'
notifications:
  email: false
