# https://developers.facebook.com/apps にてアプリを登録する
zomeki.example.com:
  id: 'App ID 1'
  secret: 'App Secret 1'
  scope: 'email'
zomeki.example.net:
  id: 'App ID 2'
  secret: 'App Secret 2'
  scope: 'email'
zomeki.example.org:
  id: 'App ID 3'
  secret: 'App Secret 3'
  scope: 'email'
