development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zomeki_development
  pool: 5
  username: zomeki
  password: zomekipass
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zomeki_test
  pool: 5
  username: zomeki
  password: zomekipass
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zomeki_production
  pool: 5
  username: zomeki
  password: zomekipass
  host: 127.0.0.1
